server:
  port: 9004
  address: 0.0.0.0
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: LibrarianService
          uri: lb://LibrarianService
          predicates:
            - Path=/healthybooks/librarianService/**

        - id: borrowerService
          uri: lb://borrowerService
          predicates:
            - Path=/healthybooks/borrowerService/**


        - id: libraryManagementService
          uri: lb://libraryManagementService
          predicates:
            - Path=/healthybooks/libraryManagementService/**
eureka:
  instance:
    hostname: lms-api-gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://lms-server:8761/eureka/